/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kqK0ogO62km
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function CreateZone() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="mx-auto max-w-2xl space-y-8">
          <div className="space-y-2 text-center">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Crear Nueva Zona</h1>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Define los detalles de la nueva zona que deseas crear.
            </p>
          </div>
          <Card>
            <CardContent className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="name">Nombre de la Zona</Label>
                <Input id="name" placeholder="Ingresa el nombre de la zona" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="description">Descripción</Label>
                <Textarea
                  className="min-h-[150px]"
                  id="description"
                  placeholder="Ingresa una breve descripción de la zona" />
              </div>
            </CardContent>
            <CardFooter>
              <Button className="w-full">Crear Zona</Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </section>)
  );
}
